### PR TITLE
Update data_utils.py

### PR DESCRIPTION
**Pull request by Anri-Lombard**
Reference: https://discuss.huggingface.co/t/typeerror-due-to-load-dataset/58846/2

The error mentioned in the above thread occurs when passing through the normal data_path, but converting to string solves it for me.

Would be awesome to release this to the safe-mol library so we could continue training with the library instead of downloading all the files and handling them locally 🙏

## Changelogs

- _enumerate the changes of that PR._

Just converting the path to string.

---

_Checklist:_

- [ ] _Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate)._
- [ ] _Update the API documentation if a new function is added, or an existing one is deleted. Eventually consider making a new tutorial for new features._
- [ ] _Write concise and explanatory changelogs below._
- [ ] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_

### CODE REVIEW

**Comment by maclandrol** [comment]
Hi @Anri-Lombard, could you run the code formatter and linters ? We use black and ruff.

**Comment by Anri-Lombard** [comment]
Sure thing @maclandrol; `ruff check` passed all tests and `ruff format` reformatted 9 files. When I run `black .` it also runs 8 files, so that is contradictory. But I believe the PR already passed all black checks.

**Comment by maclandrol** [comment]
It's likely something to do with the version that you have locally and the one that is used on the CI.

On the CI, the ruff version is `ruff-0.5.1` and black is `black>=24`.

**Comment by Anri-Lombard** [comment]
Oh dang...

**Comment by maclandrol** [comment]
Ah, that one is not you. Let me take care of that.

**Comment by maclandrol** [comment]
@Anri-Lombard  I merged and will address in #47. All good. I will release when deployed

**Comment by Anri-Lombard** [comment]
Perfect; Thanks @maclandrol. Looking forward to using the cli again 🙌

**Comment by maclandrol** [comment]
@Anri-Lombard FYI, you should have the newly released SAFE model available already.

**Pull request merged**
