### PR TITLE
make sure tokenizer can be loaded from pretrained in repo

### PR DESCRIPTION
**Pull request by maclandrol**
## Changelogs

- _enumerate the changes of that PR._

1. Some basic tests
2. Add support for uploading and reloading tokenizers to and from hub
3. various misc fixes
4. Push default model (last checkpoint) on `datamol-io/safe-gpt`. **Model card is still missing**
5. Add the split function to get a list of tokens from a safe string

---

_Checklist:_

- [x] _Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate)._
- [x] _Update the API documentation if a new function is added, or an existing one is deleted. Eventually consider making a new tutorial for new features._
- [x] _Write concise and explanatory changelogs below._
- [x] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

It should now be possible to do:

```python
from safe.tokenizer import SAFETokenizer
from safe.trainer.model import SAFEDoubleHeadsModel
from safe.sample import SAFEDesign

model = SAFEDoubleHeadsModel.from_pretrained("datamol-io/safe-gpt")
tokenizer = SAFETokenizer.from_pretrained("datamol-io/safe-gpt")
designer = SAFEDesign.load_default(verbose=True) # now default is "datamol-io/safe-gpt"
```

### CODE REVIEW

**Comment by maclandrol** [comment]
Model on hub here: https://huggingface.co/datamol-io/safe-gpt

**Comment by maclandrol** [comment]
Will attempt to upload dataset today. 

Will address doc issue probably tomorrow

**Comment by hadim** [comment]
Nice and thanks.

So the custom tokenizer works? It's just about specifying the custom class when loading the config no?

---

For uploading the dataset, if it's heavy, I can do it from my workstation if you want. Just give me the bucket link.

**Comment by maclandrol** [comment]
Thanks, 

Dataset here: `gs://valence-experiments/safe/data/`, I have relatively slow internet, so was going to use a vm. 

> So the custom tokenizer works? It's just about specifying the custom class when loading the config no?

Huggingface still does not support custom pretokenizers (so can't serialize the  can't upload), thus the wrapper for training the tokenizer + the custom way of saving and loading which has now been made compatible with the `PushToHubMixin`  interface. 

```AutoTokenizer.from_pretrained``` wouldn't work here (although with some efforts, it can)

**Comment by hadim** [comment]
I think I am done on my side - both datasets are on HF.

I also pushed a few tweaks to the readme on `main`.

Once done here, I can bump a new release and then we should be good for this first public release.

**Comment by maclandrol** [comment]
I am technically done here (once the CI is green, can be merged)

**Pull request merged**
